version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blog_db_admin
      POSTGRES_DB: blog_db
      POSTGRES_PASSWORD: 039240899e462c7BF8D8e0f708eeEFF13C93DEd4b5be5A86Ad245573ce6cC2c
    volumes:
      - ~/volumes/blog_db:/var/lib/postgresql/data

  web:
    command: dotnet MentorsBlog.dll --environment=dev
    volumes:
      - ~/volumes/blog_static:/app/storage
    environment:
      ASPNETCORE_ENVIRONMENT: dev
    ports:
      - "8070:80"
    restart: always
    depends_on: 
      - db
    build:
      context: .
      dockerfile: vtbbook/Dockerfile

networks:
  default:
    external:
      name: orchestr
